
services:
  db:
    image: postgres:alpine
    container_name: ims_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: imsdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d imsdb" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s


  backend:
    build: .
    container_name: ims_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/imsdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
volumes:
  postgres_db_data: